---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databases
  namespace: task-5
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: csi-ceph-hdd-gz1
