apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom-app
      gb: "12"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubedoom-app
        gb: "12"
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoom
        ports:
        - containerPort: 5900
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:          
            cpu: 10m
            memory: 50Mi